export type OpenSourceProject = {
  slug: string;
  name: string;
  logo: string;
  accent: string;
  role: 'CONTRIBUTOR' | 'COMMITTER' | 'OWNER';
  href: string;
  prHref: string;
  prLabel?: string;
  function: string;
  problem: string;
  reasoning: string;
  solution: string;
  impact: string;
  highlight: string;
  takeaway: string;
  release?: {
    label: string;
    title: string;
    href: string;
    credit: string;
    steps: string[];
    linkLabel?: string;
    showOnCard?: boolean;
  };
  visualization: 'config' | 'jaxpr' | 'reflection' | 'identity' | 'adapter' | 'axis' | 'boundary' | 'coordinate' | 'routing' | 'numeric' | 'shared-state' | 'reshape-semantics' | 'quaternion' | 'tensor-layout' | 'parallel-inputs' | 'zenflow' | 'operational-acceleration' | 'obj-whitespace' | 'empty-index' | 'fixed-lag-pending' | 'gjk-simplex' | 'frustum-culling' | 'ui-lifecycle' | 'matrix-codegen' | 'caller-immutability' | 'content-immutability' | 'token-axis-sampling' | 'path-rpe-pairs' | 'aligned-map-base' | 'nullish-zero' | 'binary-rescoring' | 'lrn-channel-axis' | 'encoded-drive-uri' | 'memory-config-immutability' | 'sparse-svd-backend' | 'trimmed-mean-boundary';
};

export const openSourceProjects: OpenSourceProject[] = [
  {
    slug: 'flower', name: 'Flower', logo: 'https://flower.ai/static/images/icon/icon.png', accent: '#2d3840', role: 'CONTRIBUTOR', href: 'https://github.com/flwrlabs/flower', prHref: 'https://github.com/flwrlabs/flower/pull/7946',
    function: '用于构建联邦 AI 系统的开源框架，通过可扩展 Strategy、ServerApp 与 ClientApp 组织跨设备训练和评估，并兼容 PyTorch、TensorFlow、JAX、Hugging Face、scikit-learn 等多种机器学习技术栈。',
    problem: 'ServerApp 与旧版 `FedTrimmedAvg` 都接受范围外的裁剪比例。`beta=0.5` 且客户端更新数为偶数时，`lowercut` 与 `uppercut` 恰好相等；旧逻辑只检查前者是否大于后者，于是空切片继续进入 `np.mean()`，产生 `NaN` 聚合参数。负值同样没有在策略初始化阶段被拒绝，而是延迟到数组分区时才失败。',
    reasoning: '`beta` 会从分布的上下两端各裁掉同一比例，因此必须满足 `0 ≤ beta < 0.5`，才能保证中央样本集合非空。约束不能只放在公开策略构造器：底层 trimmed-mean helper 也可以被直接调用，ServerApp 与 legacy strategy 又维护两套入口；四个边界必须共享同一参数域，才能避免绕过校验。',
    solution: '在 ServerApp 和 legacy `FedTrimmedAvg` 构造器中前置验证 `beta`，并在 `trim_mean()` 与 `_trim_mean()` 内同步校验各自的 cut fraction；非法值立即抛出说明 `[0, 0.5)` 的 `ValueError`，不再依赖 `lowercut > uppercut` 的间接判断。文档同步标明取值区间，参数化回归覆盖 `-0.1` 与 `0.5` 两个边界及两代实现。',
    impact: '非法裁剪配置现在会在策略创建或底层聚合入口明确失败，不会继续执行空切片均值并把 `NaN` 传播到全局模型；合法 `beta` 的分区和聚合路径保持不变。改动覆盖 6 个文件，三组定向测试共 18 项通过，完整 Framework 检查同步通过。',
    highlight: '0 ≤ β < 0.5 · FAIL BEFORE AGGREGATION',
    takeaway: '在聚合开始前拒绝会把双尾样本全部裁空的 beta',
    visualization: 'trimmed-mean-boundary',
  },
  {
    slug: 'tensorly', name: 'TensorLy', logo: 'https://raw.githubusercontent.com/tensorly/tensorly/main/doc/_static/favicon/android-chrome-192x192.png', accent: '#355486', role: 'CONTRIBUTOR', href: 'https://github.com/tensorly/tensorly', prHref: 'https://github.com/tensorly/tensorly/pull/624',
    function: '面向张量学习的 Python 库，统一提供张量代数、CP/Tucker/TT 等分解、回归与深度张量化模型，并通过可切换后端让同一套算法运行在 NumPy、PyTorch、JAX、TensorFlow、CuPy 与 Paddle 上。',
    problem: '稀疏 NumPy 后端没有实现当前的 `svd(matrix, full_matrices=...)` 契约，Sparse Robust PCA 在奇异值阈值步骤调用 `tl.truncated_svd()` 时直接以参数不匹配终止。补齐接口后还有第二层数值问题：秩亏稀疏矩阵的 Gram 矩阵会产生零或微小负特征值，直接开方并除以奇异值会生成 NaN；收敛范数聚合还可能把稀疏零维结果隐式稠密化。',
    reasoning: 'Reduced SVD 只需要较小一侧的奇异向量，可以继续在 `A Aᵀ` 或 `Aᵀ A` 的稀疏 Gram 矩阵上求解；Full SVD 必须返回方形基，本身就是稠密结果，才适合显式交给 SciPy。对于零奇异方向，伪逆系数应当置零，而缺失的正交方向需要通过 QR 补全，不能用除零结果冒充奇异向量。',
    solution: '为稀疏后端实现完整 `svd()` 分流：非稀疏或 full-matrices 路径交由 `scipy.linalg.svd()`，稀疏 reduced 路径复用 `partial_svd()`。Gram 特征值先裁到非负区间，再仅对大于机器精度的奇异值计算倒数；宽矩阵补全 `V`、高矩阵补全 `U`，并按 `R` 对角线统一 QR 符号。同步规范化零维 norm 返回值，并用 `stack` 汇总 Robust PCA 收敛范数以保留稀疏语义。',
    impact: 'Sparse Robust PCA 现在可以完成迭代并持续返回稀疏 low-rank 与 error 张量；宽、窄两类秩亏矩阵的 reduced SVD 均保持有限值、可重构性以及 `UᵀU`、`VVᵀ` 正交约束。新增回归覆盖全部修改行，NumPy 全套测试 537 项通过、3 项跳过、1 项预期失败。',
    highlight: 'SPARSE GRAM · SAFE INVERSE · ORTHONORMAL BASIS',
    takeaway: 'Reduced SVD 保持稀疏，零奇异方向用安全倒数与 QR 补全',
    visualization: 'sparse-svd-backend',
  },
  {
    slug: 'crewai', name: 'CrewAI', logo: 'https://github.com/crewAIInc.png?size=128', accent: '#ff5a50', role: 'CONTRIBUTOR', href: 'https://github.com/crewAIInc/crewAI', prHref: 'https://github.com/crewAIInc/crewAI/pull/7068',
    function: '面向生产级多智能体系统的 Python 编排框架，通过 Crews 组织具有角色和自主性的 Agent 协作，并以 Flows 构建可控的事件驱动工作流；统一 Memory 为 Agent、任务与流程提供可分层访问和复用的长期上下文。',
    problem: '`MemoryScope.model_validate()` 与 `MemorySlice.model_validate()` 直接修改调用者传入的配置字典：`pop("memory")` 会移除运行时依赖，路径规范化会把 `scopes` 写回原映射，旧配置的判别器推断还会插入 `memory_kind`。同一份配置第一次构造后已经被消耗，第二次构造出的 scope 可能不再绑定原始 Memory，直到访问时才暴露缺失依赖。',
    reasoning: '校验器可以从输入中抽取依赖、规范化路径并补全判别器，但这些变化只属于正在生成的模型，不能成为调用者可见的副作用。这里无需深拷贝 Memory 或整个对象图：三条路径只会增删顶层键或用新列表替换 `scopes`，因此在每个即将突变的边界创建浅拷贝，就能同时隔离输入并保留 Memory 对象身份。',
    solution: '在 `_ensure_memory_kind()`、`MemoryScope._accept_memory()` 与 `MemorySlice._accept_memory()` 中分别于首次写操作前执行 `dict(value)` 或 `dict(data)`；后续 `pop`、路径整理和判别器注入全部落在私有副本。三组回归重复使用同一配置，分别断言原字典不变、两个 scope 都绑定同一 Memory、slice 内部路径被规范化但外部列表保持原样。',
    impact: 'Memory view 配置现在可以安全地跨工厂、依赖注入和重复校验复用，不会因调用顺序产生“第一次有 Memory、第二次失联”的隐蔽状态差异；序列化格式、规范化后的模型值和公开 API 均保持不变。完整 Memory 测试集 150 项通过，Ruff、格式化、mypy 与三项合并检查同步通过。',
    highlight: 'COPY CONFIG · NORMALIZE PRIVATE · REUSE SAFELY',
    takeaway: '校验只修改私有副本，让 Memory scope 配置保持可复用',
    visualization: 'memory-config-immutability',
  },
  {
    slug: 'markitdown', name: 'MarkItDown', logo: 'https://github.com/microsoft.png?size=128', accent: '#0078d4', role: 'CONTRIBUTOR', href: 'https://github.com/microsoft/markitdown', prHref: 'https://github.com/microsoft/markitdown/pull/2315',
    function: 'Microsoft 开源的轻量级 Python 文件转换工具，把 PDF、Word、PowerPoint、Excel、图片、音频、HTML、压缩包和网页等内容统一转换为适合 LLM 与文本分析流水线消费的 Markdown。',
    problem: 'Windows 下的 `file:///C%3A/Temp/example.md` 会在盘符冒号仍处于百分号编码状态时进入路径转换。旧实现先尝试识别 DOS 盘符，再由 `url2pathname()` 解码；识别阶段看不到 `C:`，解码后路径仍带前导分隔符，随后 `abspath()` 又补上当前盘符，最终得到 `C:\\C:\\Temp\\example.md` 并以 `OSError: Invalid argument` 终止转换。',
    reasoning: '问题不在于所有绝对路径都应去掉首字符，而在于解码后才出现的 Windows 盘符语法。修复必须发生在 `url2pathname()` 之后、`abspath()` 之前，并同时满足三个条件：运行于 Windows、路径以 `/` 或 `\\` 开头、紧随其后的第二个字符位置是盘符冒号。这样才能只处理 `/C:/...`，而不改变 POSIX 根路径、UNC 网络路径或普通相对路径。',
    solution: '先保存 `url2pathname(parsed.path)` 的结果；仅当 `os.name == "nt"`、首字符为路径分隔符且 `path[2:3] == ":"` 时移除一个前导分隔符，再交给 `os.path.abspath()`。回归测试通过 `ntpath`、Windows 版 `url2pathname` 与隔离的 `os` 替身，在任意 CI 平台复现 Windows 路径语义，并断言编码 URI 精确解析为 `C:\\Temp\\example.md`。',
    impact: '百分号编码与未编码的 Windows 盘符 URI 现在会收敛到同一个本地路径，`convert_uri()` 不再因重复盘符而在打开文件前失败；POSIX 与 UNC 路径保持原有行为。合并版本通过 337 项测试、4 项跳过，并完成类型检查、全仓预提交检查与三项合并检查。',
    highlight: 'DECODE → DETECT DRIVE → NORMALIZE',
    takeaway: '在绝对化之前识别解码后的盘符，只修正 Windows file URI',
    visualization: 'encoded-drive-uri',
  },
  {
    slug: 'onnx', name: 'ONNX', logo: 'https://raw.githubusercontent.com/onnx/onnx/main/docs/docsgen/source/onnx-favicon.png', accent: '#005ced', role: 'CONTRIBUTOR', href: 'https://github.com/onnx/onnx', prHref: 'https://github.com/onnx/onnx/pull/8331',
    function: '面向机器学习模型互操作的开放标准与参考实现，定义统一的计算图、算子规范和序列化格式，并提供模型检查、形状推断、参考执行器与后端一致性测试，连接训练框架、编译器和推理运行时。',
    problem: 'LRN 规范把输入定义为 `(N, C, D1, ..., Dn)`，归一化窗口应沿通道轴 `C` 滑动；旧参考实现却用 `range(x.shape[0])` 遍历 batch 数，再把循环索引写到 `square_sum[:, c, :, :]` 的通道位置。当 `N < C` 时部分通道永远保持零归一化和，当 `N > C` 时则会越过通道边界；硬编码四维切片还拒绝规范允许的 3D、5D 等输入。',
    reasoning: 'LRN 对每个 batch 和空间位置独立计算相邻通道的平方和，因此循环边界与窗口上下限都只能来自 `x.shape[1]`。空间维数量并不参与通道选择，应该通过省略号原样传递；输出缓冲区也应继承输入的形状与 dtype，避免实现额外制造维度和类型假设。',
    solution: '引入 `channel_count = x.shape[1]`，按通道数迭代并以同一计数裁剪窗口，使用 `square_sum[:, c, ...] = sum(x[:, begin:end, ...] ** 2, axis=1)` 统一处理任意空间维；最低秩约束从固定 4D 改为至少包含 batch 与 channel 的 2D。同步更新生成的后端用例，并新增奇偶窗口、边界通道、3D/4D/5D、零通道以及 float16、float32、float64、bfloat16 覆盖。',
    impact: 'LRN 参考执行器现在在 batch 与 channel 数不相等时仍会完整归一化每个通道，不再留下错误零值或触发越界；同一实现也忠实支持规范中的任意空间维输入和全部支持 dtype。参考执行器测试 310 项通过、4 项跳过，LRN 后端测试 2 项通过、2 项跳过，完整 lint 同步通过。',
    highlight: 'ITERATE C · PRESERVE N · GENERALIZE D₁…Dₙ',
    takeaway: '沿通道轴计算 LRN，并让参考实现覆盖任意空间维',
    visualization: 'lrn-channel-axis',
  },
  {
    slug: 'sentence-transformers', name: 'Sentence Transformers', logo: 'https://github.com/huggingface.png?size=128', accent: '#e59b18', role: 'CONTRIBUTOR', href: 'https://github.com/huggingface/sentence-transformers', prHref: 'https://github.com/huggingface/sentence-transformers/pull/3948',
    function: 'Hugging Face 维护的嵌入、语义检索与重排序框架，统一支持 Sentence Transformer、Cross Encoder、Sparse Encoder 与 Multi-Vector Encoder，并提供量化向量搜索和多种后端集成。',
    problem: '`binary` 量化会把 `np.packbits` 生成的无符号字节减去 128，以 `int8` 存入 Usearch；重排阶段却直接把取回的有符号字节转换为 `uint8`，相当于翻转每个字节的最高位，点积分数和最终排序都会被改写。同时，`packbits` 会把维度补齐到整字节，未裁掉的填充位会让非 8 倍数维度在重排时发生形状不匹配。',
    reasoning: 'Usearch 返回的是索引中真实存储的 `int8`，并不会自动恢复量化前的字节域；解包前必须先在更宽的整数类型中加回 128，避免 NumPy 对 `int8 + 128` 的溢出限制。位解包后还必须以原始查询维度为唯一边界裁剪尾部 padding，否则候选向量与查询不再属于同一向量空间。',
    solution: '在 Usearch 重排路径中先执行 `int8 → int16 → +128 → uint8`，恢复原始 packed bytes，再用 `[..., :query_dim]` 裁掉解包后的尾部填充位。新增真实索引回归，分别验证 signed binary 的排序正确性和非字节对齐维度；合并版本同时把 padding 修复扩展到 FAISS，并为量化 EmbeddingSimilarityEvaluator 补齐浮点转换与精度覆盖。',
    impact: '修复前，候选池越大反而越容易得到错误排序：维护者对 200 条语料实测，`rescore_multiplier` 从 2、8 增至 40 时，Recall@5 由 0.48、0.28 降到 0.24；修复后分别恢复为 0.66、0.98 和 1.00，并与暴力点积排序完全一致。非 8 倍数维度也不再因 padding 导致广播错误。',
    highlight: 'RESTORE BYTE · TRIM BITS · RECOVER RANKING',
    takeaway: '还原 signed binary 字节域，并裁掉填充位以恢复正确排序',
    visualization: 'binary-rescoring',
  },
  {
    slug: 'sillytavern', name: 'SillyTavern', logo: 'https://raw.githubusercontent.com/SillyTavern/SillyTavern/release/public/img/logo.png', accent: '#d61f26', role: 'CONTRIBUTOR', href: 'https://github.com/SillyTavern/SillyTavern', prHref: 'https://github.com/SillyTavern/SillyTavern/pull/5965',
    function: '面向高级用户的本地 LLM 前端，统一管理多模型 API、角色卡、提示词、世界书、生成参数与扩展能力，可连接 NovelAI、OpenAI、Claude、本地推理服务等多种后端。',
    problem: 'NovelAI Math1 Linear 的 `math1_temp` 合法范围包含 `0`，但预设加载器和已保存设置加载器都使用 `value || 1` 提供默认值。JavaScript 会把数值零判为 falsy，因此用户明确保存的 `0` 会在加载时被静默改成 `1`，实际生成温度与界面配置不一致。',
    reasoning: '这里需要区分的是“字段不存在”和“字段存在但值为零”，而不是一般的真假值。逻辑或运算符把 `0`、`null` 与 `undefined` 都折叠到同一默认分支，破坏了参数取值域；空值合并运算符只在 `null/undefined` 时回退，正好表达设置加载的存在性契约。',
    solution: '在 `loadNovelPreset()` 与 `loadNovelSettings()` 两条入口中，把 `math1_temp || 1` 同步替换为 `math1_temp ?? 1`。新增独立单元测试，先加载 `math1_temp: 0` 的已保存设置，再加载同值预设，分别断言全局 NovelAI 配置仍保持精确的数值零。',
    impact: 'Math1 Linear 用户现在可以可靠保存、恢复并切换零温度配置；字段真正缺失时仍会得到默认值 `1`，原有兼容行为不变。两种加载来源均由回归覆盖，避免未来只修复其中一条路径而重新产生配置漂移。',
    highlight: '0 IS A VALUE · NULL IS ABSENCE',
    takeaway: '保留合法零值，只为空缺设置应用默认温度',
    visualization: 'nullish-zero',
  },
  {
    slug: 'pinocchio', name: 'Pinocchio', logo: 'https://github.com/stack-of-tasks.png?size=128', accent: '#b84622', role: 'CONTRIBUTOR', href: 'https://github.com/stack-of-tasks/pinocchio', prHref: 'https://github.com/stack-of-tasks/pinocchio/pull/2940',
    function: '面向机器人系统的高性能刚体动力学库，提供运动学、动力学、解析导数、约束与碰撞等算法，并通过 C++、Python、ROS 和多种自动微分后端服务于控制、优化与仿真。',
    problem: '`compare_maps()` 以 `Eigen::MapBase<D, Level>` 接收操作数。对于 `Eigen::Map<RowVector, Eigen::Aligned16>` 这类对齐动态行向量，GCC 10 发现具体 Map 类型存在歧义的 `MapBase` 基类路径，无法完成模板实参推导，使 `MatrixStackTpl::operator==` 在编译阶段直接失败。',
    reasoning: '这个 helper 实际只依赖矩阵表达式共有的 `rows()`、`cols()` 与逐元素比较，并不读取 Map 的对齐方式、访问级别或存储映射能力。函数签名绑定 `MapBase` 不仅暴露了不需要的继承细节，还额外引入两个 `Level` 模板参数；正确契约应是稳定且无歧义的 `MatrixBase` 表达式接口。',
    solution: '将两个形参改为 `const Eigen::MatrixBase<D>&`，模板参数从 `D1, Level1, D2, Level2` 收敛为 `D1, D2`；函数体仍先比较行列数，再执行原有的精确元素比较。已有 `MatrixStackTpl::operator==` 测试继续覆盖该路径，无需添加只验证内部 helper 的重复用例。',
    impact: '对齐 Map 在 GCC 10 下重新获得可推导的唯一参数转换路径，`MatrixStackTpl` 相等比较可以正常编译，同时未改变尺寸不匹配和精确比较语义。Eigen 3.4 与 5.0.1 两套构建分别完成 312/314 个步骤，并各自通过 136 项测试。',
    highlight: 'MAP STORAGE ≠ MATRIX EXPRESSION CONTRACT',
    takeaway: '用 MatrixBase 表达比较契约，避开对齐 Map 的继承歧义',
    visualization: 'aligned-map-base',
  },
  {
    slug: 'evo', name: 'evo', logo: 'https://github.com/MichaelGrupp.png?size=128', accent: '#356ba6', role: 'CONTRIBUTOR', href: 'https://github.com/MichaelGrupp/evo', prHref: 'https://github.com/MichaelGrupp/evo/pull/778',
    function: '面向里程计与 SLAM 系统的 Python 评测工具，提供轨迹对齐、绝对位姿误差（APE）、相对位姿误差（RPE）、结果统计和可视化，支持 KITTI、TUM、EuRoC 等常见轨迹格式。',
    problem: '距离型 RPE 在 `all_pairs=False` 时只收集累计路径首次达到各个距离阈值的 pose，再把相邻端点配成非重叠区间，却没有把 pose 0 放入端点列表。对于位置为 `0, 1, 2, 3, 4 m`、`delta=2 m` 的直线路径，旧逻辑只返回 `(2, 4)`，完整漏掉 `(0, 2)`，使轨迹起始阶段的误差不进入统计。',
    reasoning: '连续 RPE pair 的端点列表描述整条轨迹的区间边界，而第一条边界必须是起点。仅在达到阈值时记录终点，会天然丢失首段；但如果从 pose 0 重新参与距离累积，又会构造起点与自身的无效关系。因此应先固定起点，再从第二个 pose 开始累计实际路程。',
    solution: '将连续模式的端点初始化为 `ids = [0]`，随后使用 `enumerate(poses[1:], start=1)` 从 pose 1 开始累积距离，保留原始全局索引；阈值判断、区间清零以及 `all_pairs=True` 路径均保持不变。回归用五个等距 pose 直接锁定 `[(0, 2), (2, 4)]`。',
    impact: '非重叠的米制 RPE 现在从轨迹起点开始形成完整分段，不再少算一个区间或忽略开头累计的位姿误差；行为也与基于 frame 和 angle 的连续过滤器保持一致。针对过滤器的 11 项测试、全量 111 项测试以及类型检查全部通过。',
    highlight: 'POSE 0 → FIRST RPE SEGMENT',
    takeaway: '从轨迹起点建立距离区间，不再漏算第一段 RPE',
    visualization: 'path-rpe-pairs',
  },
  {
    slug: 'vit-pytorch', name: 'vit-pytorch', logo: 'https://github.com/lucidrains.png?size=128', accent: '#6c4de6', role: 'CONTRIBUTOR', href: 'https://github.com/lucidrains/vit-pytorch', prHref: 'https://github.com/lucidrains/vit-pytorch/pull/370',
    function: '面向视觉 Transformer 研究的 PyTorch 实现集合，覆盖 ViT、DeiT、CaiT、CrossViT、NaViT 等大量架构与训练变体，并提供可直接组合的注意力、正则化和特征学习模块。',
    problem: '`DecorrelationLoss(sample_frac < 1)` 会先把输入打包，再仅依据前两个维度生成随机索引。面对 ViT 产生的 `[layer, batch, token, dim]` 张量时，这些索引实际落在 batch 轴：序列长度完全没有减少，batch 却可能被重新排序或重复，最终损失并未计算预期的 token 子集。',
    reasoning: '采样比例描述的是每个样本内部的 token 数量，因此无论前面存在多少层维或批次维，都必须保持这些 leading dimensions 原位，只沿倒数第二个 token 轴缩短 `N → k`。索引还要为每组前导坐标独立生成，并在特征维展开后交给同一条 gather 操作。',
    solution: '直接从 `tokens.shape[:-1]` 生成随机分数，在最后一维排序并截取 `num_sampled` 个 token 索引；将索引扩展到 embedding 维后执行 `tokens.gather(-2, indices)`，删除 pack / unpack、batch arange 与高级索引。固定随机种子的回归将结果与显式选出的同一 token 子集逐项比较。',
    impact: '`sample_frac=0.5` 现在会把每个 layer / batch 的 token 维从 4 正确缩到 2，而不会改写或复制 batch；任意前导维均保持不变，损失值与显式子集计算一致。完整 ViT 前向与反向传播也通过验证，采样路径重新符合参数语义。',
    highlight: 'KEEP LAYER + BATCH · SAMPLE TOKEN AXIS',
    takeaway: '保持所有前导维，只沿 token 轴执行独立采样',
    visualization: 'token-axis-sampling',
  },
  {
    slug: 'langchain', name: 'LangChain', logo: 'https://github.com/langchain-ai.png?size=128', accent: '#1c3c3c', role: 'CONTRIBUTOR', href: 'https://github.com/langchain-ai/langchain', prHref: 'https://github.com/langchain-ai/langchain/issues/39821', prLabel: '查看我的 Issue',
    function: '面向 Agent 与 LLM 应用的开源 Python 框架，通过统一的模型、消息、工具、检索与中间件接口连接不同提供商和组件，为可组合、可扩展的智能体工程提供核心基础设施。',
    problem: 'Bedrock Converse 消息的 `AIMessage.content_blocks` 看似只是读取派生表示，实际却会改写源 `message.content`：字符串会被替换成文本块列表，未知字典块的 `index` 会被 `pop()` 移除。第一次读取已经污染原始消息，连续两次读取还可能返回不同结果。',
    reasoning: '`content_blocks` 是只读属性，调用方应能安全地重复读取，并继续序列化、持久化原始 provider 内容。修复边界不在于深拷贝整个消息，而是让字符串转换只使用局部列表，并在提升未知块的 `index` 前复制该字典，从最小范围切断写回源对象的路径。',
    solution: '字符串内容只在局部列表中转换，不再写回 `message.content`；处理未知字典块时先复制对象，再从副本提升 `index`。参数化回归覆盖 `AIMessage` / `AIMessageChunk`、字符串、自定义块及连续读取，直接锁定派生视图与源对象之间的只读边界。',
    impact: '读取 `content_blocks` 不再改变原始字符串或删除未知块的 `index`；同一消息的连续读取保持一致，后续序列化与持久化仍能获得完整的 provider 原始内容。两类消息对象与两条原地修改路径均由回归测试覆盖。',
    highlight: 'READ → DERIVE · SOURCE UNCHANGED',
    takeaway: '让 content_blocks 成为真正只读、可重复的消息视图',
    release: {
      label: 'MERGED · CO-AUTHORED',
      title: 'Issue #39821 已转化为 LangChain 上游修复',
      href: 'https://github.com/langchain-ai/langchain/commit/36f0d10348b0e5c4917602d80cc1b5f0ced1da8a',
      credit: '维护者通过 PR #40022 合并修复，并在最终提交中以 Co-authored-by 明确保留 Zhewen Tan（@tandede）的共同作者署名。',
      steps: ['Issue #39821 最小复现与根因定位', 'PR #40022 合入 master', 'Merge Commit 共同作者署名'],
      linkLabel: '查看合并提交',
      showOnCard: false,
    },
    visualization: 'content-immutability',
  },
  {
    slug: 'instructor', name: 'Instructor', logo: 'https://github.com/567-labs.png?size=128', accent: '#5b4cf0', role: 'CONTRIBUTOR', href: 'https://github.com/567-labs/instructor', prHref: 'https://github.com/567-labs/instructor/pull/2551',
    function: '基于 Pydantic 的 LLM 结构化输出框架，将响应模型、验证、重试与多提供商适配统一到类型安全的 Python 接口，支持 OpenAI、Anthropic、Gemini、Bedrock 等主流模型服务。',
    problem: '`update_gemini_kwargs()` 虽然复制了最外层请求参数，却继续复用调用者传入的嵌套 `safety_settings` 映射；合并 Gemini 默认阈值时会原地修改应用持有的配置，使同一字典在后续请求中携带 Instructor 写入的状态。',
    reasoning: '外层浅拷贝只隔离字典壳，不能改变嵌套可变对象仍被共享的事实。请求规范化应把调用方输入视为只读：既要把默认阈值写入即将发送的请求，也必须保证返回映射与原对象不再别名，避免一次调用改变之后的应用行为。',
    solution: '在应用默认阈值前显式复制 `safety_settings`，再把独立映射写回结果；回归测试同时锁定三条契约：原始配置保持不变、输出不与输入共享对象身份、发送给 Gemini 的默认安全阈值仍然完整生效。',
    impact: '调用者传入的安全配置在请求前后保持内容与对象边界稳定，返回映射则拥有独立的嵌套设置；默认阈值仍能完整补齐。复用同一配置发起多次请求时，后一次行为不再受前一次规范化过程影响。',
    highlight: 'COPY → MERGE → NO MUTATION',
    takeaway: '默认安全阈值照常生效，调用者配置始终保持只读',
    visualization: 'caller-immutability',
  },
  {
    slug: 'webots', name: 'Webots', logo: 'https://github.com/cyberbotics.png?size=128', accent: '#e1261c', role: 'CONTRIBUTOR', href: 'https://github.com/cyberbotics/webots', prHref: 'https://github.com/cyberbotics/webots/pull/7009#pullrequestreview-5006270169',
    function: 'Cyberbotics 维护的开源机器人仿真平台，用于建模、编程和仿真机器人、车辆与机械系统，覆盖三维物理环境、传感器、控制器以及 ROS / ROS 2 工作流。',
    problem: '负单位四元数 `(-1, 0, 0, 0)` 与正单位四元数描述相同的恒等旋转，但旧转换会得到 2π 角度并继续归一化零长度向量，除零后生成 NaN 旋转轴，可能沿场景树或渲染路径触发崩溃。',
    reasoning: '四元数 q 与 −q 表示同一个三维旋转；当向量部分范数接近零时，不论标量符号如何都应落到恒等旋转。同时，向量部分非零的负标量四元数仍需保留原有轴与旋转角，不能被一概折叠。',
    solution: '在 `WbRotation::fromQuaternion()` 中只计算一次向量范数；遇到近零向量时直接返回有限的规范恒等轴角 `(0, 0, 1, 0)`，其余输入复用该范数继续正常归一化，并补充变更记录。',
    impact: '负单位、近退化与正单位四元数都稳定得到有限轴角，不再把合法恒等姿态扩散成 NaN；非退化负标量输入仍保留预期旋转。转换结果因此可以安全进入场景树、渲染和物理仿真链路。',
    highlight: 'CONTRIBUTOR → COMMITTER',
    takeaway: '修复退化四元数崩溃，并获邀成为 Committer',
    release: {
      label: 'NIGHTLY · 27 AUG',
      title: 'PR #7009 已进入 Webots 2026-08-27 Nightly Build',
      href: 'https://github.com/cyberbotics/webots/releases/tag/nightly_27_8_2026',
      credit: '官方 Nightly 标签已经完整包含四元数转换修复的合并提交。这是 Webots 的官方预发布构建，项目同时明确提示它可能不稳定，因此不将其表述为稳定版。',
      steps: ['负单位四元数转换修复', 'Nightly 标签包含合并提交', '官方预发布构建'],
      linkLabel: '查看 Nightly 构建',
    },
    visualization: 'quaternion',
  },
  {
    slug: 'robotics-toolbox-python', name: 'Robotics Toolbox', logo: 'https://raw.githubusercontent.com/petercorke/robotics-toolbox-python/main/docs/figs/RobToolBox_RoundLogoB.png', accent: '#2f6f9f', role: 'CONTRIBUTOR', href: 'https://github.com/petercorke/robotics-toolbox-python', prHref: 'https://github.com/petercorke/robotics-toolbox-python/pull/629',
    function: '面向机器人研究与教学的 Python 工具箱，覆盖串联机械臂的运动学与动力学、雅可比矩阵、轨迹规划和控制，并提供 Puma 560、Franka Panda 等 50 余种机器人模型。',
    problem: '`DynamicsMixin.accel_x()` 的正常调用会走到未定义的 `T` 与 `J`，使 1.4.0 公开 API 直接抛出 `NameError`；同时结果缓冲区错误地使用关节数 `self.n` 作为列数，7 轴冗余机器人无法返回应有的六维笛卡尔加速度。',
    reasoning: '调用入口提供的是操作空间速度 `xd`。由 `xd = Ja · qd` 恢复关节速度后，末端加速度必须同时包含解析雅可比的时间导数项与关节加速度映射：`xdd = Jad · qd + Ja · qdd`。原实现混用了未生成的变换矩阵与几何雅可比，还隐含假设其变换导数为零。',
    solution: '复用现有 `jacob0_analytical()` 与带同一角度表示的 `jacob0_dot()`，直接计算完整解析关系；将单点和轨迹输出统一为固定 6 维，并同步修正文档中的速度、外力和轨迹形状语义。',
    impact: 'Puma 560 的单点与轨迹输入现在都能得到有限、维度一致的末端加速度；7 轴 Panda 也稳定返回六维笛卡尔向量，而不会把关节数泄漏到输出形状。速度、加速度和轨迹接口重新共享同一套操作空间语义。',
    highlight: 'xdd = J̇a q̇ + Ja q̈',
    takeaway: '恢复六维末端加速度的完整动力学关系',
    release: {
      label: 'v1.4.1',
      title: 'PR #629 已随 Robotics Toolbox v1.4.1 正式发布',
      href: 'https://github.com/petercorke/robotics-toolbox-python/releases/tag/v1.4.1',
      credit: 'v1.4.1 的 Bug Fixes 以“compute accel_x with analytical Jacobian derivative”单独列出这项修复；正式版本标签完整包含 PR #629 的合并提交。',
      steps: ['解析雅可比导数修复', 'v1.4.1 Release Notes 收录', '正式版本标签包含合并提交'],
    },
    visualization: 'operational-acceleration',
  },
  {
    slug: 'simbody', name: 'Simbody', logo: 'https://github.com/simbody.png?size=128', accent: '#26799e', role: 'CONTRIBUTOR', href: 'https://github.com/simbody/simbody', prHref: 'https://github.com/simbody/simbody/pull/863',
    function: '高性能 C++ 多体动力学与物理仿真库，用于模拟人体骨骼、机器人、车辆等关节化生物力学与机械系统，是 OpenSim 等科学计算项目的底层基础设施。',
    problem: 'OBJ 面片解析循环已经通过格式化流提取读取每个 `v/vt/vn` token，却在每次读取后额外执行 `ignore(..., \' \')`。当分隔符是 Tab、垂直制表符或换页符而不是字面空格时，这次查找会越过分隔符并继续吞掉后续顶点，四边形最终被解析成少于四个顶点。',
    reasoning: '`operator>>` 本身会跳过 C++ 流所识别的全部前导空白，并以空白作为 token 边界；额外寻找字面空格与既有提取机制职责重叠。真正需要保留的是斜杠分隔的顶点、纹理和法线索引语义，以及反斜杠续行，而不是再建立第二套分隔规则。',
    solution: '删除 token 提取后的冗余字面空格 `ignore`，让格式化提取成为唯一的空白处理路径；新增包含 Tab、垂直制表符、换页符、重复空格和续行的双面片用例，并逐项验证顶点、纹理坐标与法线索引。',
    impact: '普通与续行 OBJ 面片现在都能在空格、Tab、垂直制表符和换页符混用时完整保留四个顶点及对应 `v/vt/vn` 三元组；不会再因分隔符差异吞掉后续 token。项目 114/114 项测试保持通过。',
    highlight: 'FORMATTED EXTRACTION > LITERAL SPACE',
    takeaway: '不再让空格查找吞掉后续 OBJ 顶点',
    visualization: 'obj-whitespace',
  },
  {
    slug: 'faiss', name: 'Faiss', logo: 'https://github.com/facebookresearch.png?size=128', accent: '#0668e1', role: 'CONTRIBUTOR', href: 'https://github.com/facebookresearch/faiss', prHref: 'https://github.com/facebookresearch/faiss/pull/5528',
    function: 'Meta Fundamental AI Research 维护的高性能向量相似度搜索与聚类库，使用 C++ 实现并提供完整 Python / NumPy 接口，支持 CPU、GPU 以及十亿级稠密向量索引。',
    problem: '空 `IndexFlat` 在小查询批次下会正确返回距离哨兵值与 `-1` 标签，但当 `nq × d` 达到 BLAS 分发阈值后，BLAS helper 会因 `ny == 0` 提前返回，结果处理器尚未初始化，调用者传入的距离与标签缓冲区可能继续保留原来的 `42` 和 `99`。',
    reasoning: '空数据库搜索仍然是一条有明确定义的公开接口：每个查询的全部槽位都必须由对应 result handler 写成中性距离和 `-1` 标签。Top1、Heap 与 Reservoir 已经各自掌握正确的哨兵语义，因此修复不应在外层复制结果规则，而应确保空索引进入能够完整执行处理器生命周期的路径。',
    solution: '在内积与 L2 两个搜索分发器中把 `ny == 0` 纳入顺序路径条件，避开 BLAS 的提前返回；回归测试强制触发原 BLAS 边界，预填输出缓冲区，并覆盖两种距离度量及 `k=1/10/150` 对应的三类 result handler。',
    impact: '空索引无论查询规模和 `k` 如何都稳定写出完整哨兵结果，不再把未初始化的调用方数据当作搜索输出；Top1、Heap 与 Reservoir 三类处理器在内积和 L2 距离下保持一致。6 组回归、49 项 Python 测试、290 项 C++ 测试及 ASan / UBSan 验证均通过。',
    highlight: 'EMPTY INDEX ≠ UNTOUCHED OUTPUT',
    takeaway: '空索引搜索也必须写出完整的哨兵结果',
    visualization: 'empty-index',
  },
  {
    slug: 'gtsam', name: 'GTSAM', logo: 'https://github.com/borglab.png?size=128', accent: '#147d92', role: 'CONTRIBUTOR', href: 'https://github.com/borglab/gtsam', prHref: 'https://github.com/borglab/gtsam/pull/2749',
    function: 'Georgia Tech Borg Lab 面向机器人与计算机视觉的平滑和建图库，以因子图与贝叶斯网络表达状态估计问题，提供 C++ 核心以及 Python、MATLAB 接口。',
    problem: '`ISAM2` 允许先把 value 放入 `newTheta`、再由后续更新中的 factor 建立连接；这类 pending value 存在线性化点中，却暂时没有 `VariableIndex` 条目或 Bayes-tree clique。旧固定时窗逻辑会把所有过期时间戳键都送入排序与叶节点边缘化，使从未连接的 value 在需要 clique 的路径中失败。',
    reasoning: '“尚未连接”与“已经失效”是两个不同状态：value 在 lag window 内必须继续保留，以便迟到的 factor 仍能接入；只有超过时窗且依旧没有 factor 或 clique 时才应直接回收。同时，当前更新中新到达的 factor 必须立刻把对应键视为 active，不能被同一轮过期判断误删。',
    solution: '从新 factor 与现有 `VariableIndex` 建立 active key 集合，将过期键拆成 connected 与 pending 两组：前者继续走约束排序和 `marginalizeLeaves`，后者直接从 ISAM2 value、增量状态及时间戳映射中清理；并让变量删除逻辑兼容从未拥有索引条目的 pending value。',
    impact: '固定时窗平滑器现在支持 value 与 factor 异步到达：时窗内迟到的 factor 可以正常连接，始终未连接的 value 则会在过期后完整回收且不触碰 Bayes-tree 边缘化。连接与未连接两条生命周期均有回归覆盖，相关四组测试与三平台检查保持通过。',
    highlight: 'VALUE FIRST · FACTOR LATER · SAFE EXPIRY',
    takeaway: '让值与因子异步到达，也能在固定时窗内安全收敛',
    visualization: 'fixed-lag-pending',
  },
  {
    slug: 'jolt-physics', name: 'Jolt Physics', logo: 'https://raw.githubusercontent.com/jrouwe/JoltPhysics/master/Docs/LogoSmall.png', accent: '#1673a5', role: 'CONTRIBUTOR', href: 'https://github.com/jrouwe/JoltPhysics', prHref: 'https://github.com/jrouwe/JoltPhysics/pull/2108',
    function: '面向游戏与 VR 的多核友好型 C++17 刚体物理和碰撞检测库，支持连续碰撞、约束、角色、车辆、布料与确定性仿真，已用于 Horizon Forbidden West 与 Death Stranding 2。',
    problem: '`GJKClosestPoint::CastShape()` 在新增支撑点无法生成更近单纯形、第二次收敛仍失败时，会返回命中却把被拒绝的点继续留在 `mP`、`mQ` 与点计数中。接触点重建因此把试探点误当作有效顶点，组成近退化三角形并产生极大的重心权重，使仅仅接触的圆柱与胶囊报告约 7.24732 米穿透深度。',
    reasoning: 'GJK 单纯形只应包含当前能够描述最近几何关系的有效支撑点；未让距离继续收敛的最后一点只是试探样本。既然第二次失败后选择接受当前命中，接触重建就必须回到加入该点之前的有效单纯形，而不能用一个几何上已被判定无效的顶点插值接触位置。',
    solution: '在失败返回前递减 `mNumPoints`，明确将最后一个无效支撑点从单纯形中弹出，让 `mP` / `mQ` 的接触点重建只读取上一个有效单纯形；同时加入使用收缩形状与凸半径的圆柱—胶囊回归用例，锁定 `fraction == 0` 且穿透深度小于 `1e-4` 米。',
    impact: '复现中的穿透深度由约 7.24732 米降至约 `4.81e-6` 米，远低于回归阈值；被拒绝的试探点不再污染接触位置和法向。Debug 与 Release 各 583 项单元测试、UBSAN 下的 GJK / EPA / CastShape 测试以及多平台确定性检查保持通过。',
    highlight: 'REJECT POINT · RESTORE SIMPLEX · REBUILD CONTACT',
    takeaway: '让接触点只由最后一个有效单纯形重建',
    visualization: 'gjk-simplex',
  },
  {
    slug: 'pytorch3d', name: 'PyTorch3D', logo: 'https://github.com/facebookresearch.png?size=128', accent: '#ee4c2c', role: 'CONTRIBUTOR', href: 'https://github.com/facebookresearch/pytorch3d', prHref: 'https://github.com/facebookresearch/pytorch3d/pull/2044',
    function: 'Meta FAIR 面向三维计算机视觉研究构建的 PyTorch 组件库，覆盖异构三角网格、几何变换、可微分渲染、点云与隐式表示，并支持自动微分、批处理和 GPU 加速。',
    problem: '`face_verts` 的布局是 `[F, 3, 3] = [face, vertex, xyz]`，旧视锥剔除却使用 `face_verts[:, axis]`，把 plane axis 当成了顶点索引，随后 `sum(1) == 3` 实际判断的是“一个顶点的三个坐标是否同时越界”，而不是“三个顶点是否在同一裁剪平面之外”。修正索引后又暴露出透视投影边界：跨越相机平面的三角形会因后方顶点经过透视除法被镜像，可能在 XY 上看似全部越界，却仍有前方部分穿过视锥。',
    reasoning: '面片只有在三个顶点都位于同一个视锥平面外时才能安全删除，因此必须沿坐标维取 `face_verts[:, :, axis]`，再以 `all(dim=1)` 聚合顶点维。对于 perspective-correct 投影，XY 的 NDC 坐标只对完全位于相机前方的面片可直接用于剔除；跨越相机平面的面片应交给后续 Z clipping 处理。正交投影不发生这种镜像，Z 轴也始终使用世界坐标。',
    solution: '把坐标访问改为 `face_verts[:, :, axis]` 并使用 `all(dim=1)` 明确表达三顶点同侧条件；在关闭剔除时提前返回，并为透视投影建立 `xy_cullable` 掩码：只有全部顶点满足 `z >= z_clip_value`（未设置时为 `z > 0`）才执行 XY 剔除。回归测试覆盖六个视锥平面、三种顶点顺序、透视投影有无 Z clip、正交投影及 Z 轴剔除。',
    impact: '针对 4,096 个固定种子随机三角形的独立 oracle，修复后保持 0 个不一致；旧实现同一输入产生 604 个误剔除与 603 个漏剔除。六个视锥平面、不同顶点顺序、透视与正交投影的定向测试均保持正确，跨越相机平面的可见面片不再被误删。',
    highlight: 'VERTEX AXIS ≠ COORDINATE AXIS',
    takeaway: '按同一坐标检查三个顶点，并保护跨越相机平面的可见面片',
    visualization: 'frustum-culling',
  },
  {
    slug: 'rtabmap', name: 'RTAB-Map', logo: 'https://raw.githubusercontent.com/introlab/rtabmap/master/guilib/src/images/RTAB-Map.png', accent: '#273bd4', role: 'CONTRIBUTOR', href: 'https://github.com/introlab/rtabmap', prHref: 'https://github.com/introlab/rtabmap/pull/1755',
    function: '面向机器人感知与自主导航的实时外观建图系统，融合视觉、RGB-D、双目与 LiDAR 数据，覆盖回环检测、图优化、定位和三维建图，并提供 C++ 核心、Qt 桌面工具及 ROS / ROS 2 集成。',
    problem: '`DatabaseViewer::detectMoreLoopClosures()` 在验证检测选项之前就创建并显示 `ProgressDialog`。当 intra-session 与 inter-session 都关闭、同时又没有选择图节点时，函数弹出配置警告后直接返回，但已经可见的进度窗口没有任何任务可以推进或完成，因而成为无法正常收尾的孤立对话框。',
    reasoning: '进度窗口不是输入表单，而是“有效任务已经开始”的运行期资源；它的生命周期必须由同一条工作路径负责取消、推进和关闭。若请求连前置条件都不满足，就不存在可报告的进度。与其在每个错误出口补清理逻辑，不如让校验闸门支配资源创建，从控制流上保证失败发生时对话框尚不存在。',
    solution: '将原有七行 `ProgressDialog` 构造与配置代码原样移动到无效选项检查之后：错误配置现在只显示警告并返回，创建的对话框数量为零；合法配置仍沿用相同父对象、`WA_DeleteOnClose`、取消按钮、宽度与显示行为，回环检测本身没有改变。',
    impact: '无效检测请求现在只显示配置警告，不会创建任何进度资源；合法请求仍使用原有父对象、自动销毁、取消按钮和显示流程。错误路径的窗口数量归零，正常回环检测的执行行为保持不变。',
    highlight: 'VALIDATE → ALLOCATE → RUN',
    takeaway: '先验证检测任务，再创建只属于有效工作的进度对话框',
    visualization: 'ui-lifecycle',
  },
  {
    slug: 'symforce', name: 'SymForce', logo: 'https://github.com/symforce-org.png?size=128', accent: '#3979d4', role: 'CONTRIBUTOR', href: 'https://github.com/symforce-org/symforce', prHref: 'https://github.com/symforce-org/symforce/pull/467',
    function: '面向机器人系统的高性能符号计算、代码生成与非线性优化库，将 Python 中的几何和符号模型转换为可部署的 C++、Rust 等运行时代码，并服务于 SLAM、计算机视觉、运动规划和自主系统。',
    problem: 'Rust codegen 的单返回值路径把所有 `Matrix` 都格式化为 `nalgebra::SVector<scalar, rows × cols>`。这虽然保留了元素数量，却丢失二维形状：`Matrix23` 的函数签名和构造器都会变成 `SVector<f64, 6>`，调用方在 Rust 类型系统中再也看不到 2 行、3 列的矩阵语义。',
    reasoning: '元素数量相同不等于类型等价，`2×3`、`3×2` 与 `6×1` 必须拥有不同的静态形状。项目的多输出路径已经用 `format_typename` 正确区分向量和矩阵，因此单返回值不应另写一套压平规则；同时，返回签名与实际构造器必须复用同一个判断，否则生成代码仍会出现类型不一致。',
    solution: '在单返回值模板的两处关键位置——函数返回类型和返回值构造器——把 `format_vector` 统一替换为现有的 shape-aware `format_typename`。新增非方阵 `Matrix23` 回归，让 SymEngine 与 SymPy 两个后端都生成并编译 `SMatrix<f64, 2, 3>`；原有 `Matrix31` 则继续保持 `SVector<f64, 3>`。',
    impact: '`2×3` 等非方阵在生成的 Rust 签名与返回构造器中都保持 `SMatrix` 形状，列向量继续使用 `SVector`，两个符号后端不再产生类型分歧。回归覆盖 Python 3.10–3.14、GCC、Clang、macOS、x86_64 与 aarch64 构建。',
    highlight: 'ELEMENT COUNT ≠ MATRIX SHAPE',
    takeaway: '让 2×3 矩阵在 Rust 类型系统中仍然保持 2×3',
    visualization: 'matrix-codegen',
  },
  {
    slug: 'lm-evaluation-harness', name: 'LM Evaluation Harness', logo: 'https://github.com/EleutherAI.png?size=128', accent: '#313131', role: 'CONTRIBUTOR', href: 'https://github.com/EleutherAI/lm-evaluation-harness', prHref: 'https://github.com/EleutherAI/lm-evaluation-harness/pull/4020',
    function: '广泛使用的大语言模型评测框架，将任务定义、few-shot 模板、生成参数和推理后端统一到可复现流水线，支持跨模型、跨基准的标准化比较。',
    problem: '启用延迟注解后，dataclass 字段保存的是推迟求值的类型描述，`f.type is dict` 不再成立。CLI 会把 `model_args` 等字典参数解析成映射，纯 YAML 入口却可能把同样的 `"pretrained=gpt2,dtype=float16"` 一路保留为字符串，直到元数据与模型配置阶段才暴露类型错位。',
    reasoning: '问题不在某个参数，而在配置入口缺少共同的规范化边界。项目已经用 `DICT_KEYS` 维护 CLI 风格字典字段的单一清单，因此类型识别不应依赖注解对象身份；字符串字典还必须在任何元信息消费之前解析，同时让原生 YAML mapping 保持原状。',
    solution: '以现有 `DICT_KEYS` 取代 `f.type is dict`，并把字典字符串解析前移到 `from_config()` 与 `from_cli()` 共享的配置流水线；将 `trackio_args` 纳入同一注册表。回归同时覆盖 YAML 字符串、原生映射及两种入口，验证规范化发生在模型配置构建之前。',
    impact: '相同的评测参数现在从 CLI 与 YAML 进入后会得到一致的运行时映射，不再因延迟注解静默绕过解析；原生 YAML 字典不会被重复转换。针对配置子命令的 70 项测试和主体测试集的 613 项用例共同锁定这条入口契约。',
    highlight: 'ONE CONFIG PATH',
    takeaway: '让 CLI 与 YAML 配置进入同一条解析路径',
    release: {
      label: 'v0.4.13',
      title: 'PR #4020 已随 LM Evaluation Harness v0.4.13 正式发布',
      href: 'https://github.com/EleutherAI/lm-evaluation-harness/releases/tag/v0.4.13',
      credit: 'v0.4.13 Release Notes 将 YAML 字典字符串解析修复列入配置正确性更新，并在变更清单与 New Contributors 中署名 @tandede。',
      steps: ['CLI / YAML 配置统一解析', 'Release Notes 收录 PR #4020', 'New Contributors 官方署名'],
    },
    visualization: 'config',
  },
  {
    slug: 'numpyro', name: 'NumPyro', logo: 'https://github.com/pyro-ppl.png?size=128', accent: '#e94b2a', role: 'CONTRIBUTOR', href: 'https://github.com/pyro-ppl/numpyro', prHref: 'https://github.com/pyro-ppl/numpyro/pull/2245',
    function: '建立在 JAX 之上的概率编程框架，覆盖 HMC、NUTS、SVI 等贝叶斯推断算法，并利用 JIT、自动微分和多设备并行提升推断效率。',
    problem: 'JAX 0.11.1 的私有 `trace_to_jaxpr_dynamic` 会把闭包捕获的数组常量提升进 `jaxpr.invars`，NumPyro 却只为显式关键字参数生成 provenance 集合。两组序列长度因此不一致，只要被追踪函数闭包中含有数组常量，变量与来源信息就会错位或直接触发映射失败。',
    reasoning: '闭包常量参与计算，但不属于调用方显式提供的动态输入，也不应继承任何输入 provenance。根因是旧实现依赖了私有 tracing API 的输入布局；要恢复一一对应关系，必须在表示层明确区分 `constvars` 与 `invars`，而不是按位置补齐错误序列。',
    solution: '改用公共 `jax.make_jaxpr` 获取 `ClosedJaxpr`，让闭包常量与显式输入分别进入常量和动态参数通道；同步适配 JAX 0.11.1 的 `call_jaxpr` 绑定方式，并加入捕获数组常量的回归用例，直接验证关键字参数与 provenance 的位置对应。',
    impact: '闭包常量现在保持空 provenance，显式参数则重新与 `jaxpr.invars` 精确对齐；JAX 0.11.1 下相关 415 项测试通过，同时在 JAX 0.7.0 上保持兼容。实现也不再直接耦合容易变化的私有 partial-evaluation API。',
    highlight: 'PUBLIC JAXPR',
    takeaway: '用公共 JAXPR 接口恢复输入映射',
    visualization: 'jaxpr',
  },
  {
    slug: 'opencv', name: 'OpenCV', logo: '/logos/opencv.svg', accent: '#6652d9', role: 'CONTRIBUTOR', href: 'https://github.com/opencv/opencv', prHref: 'https://github.com/opencv/opencv/pull/29751',
    function: '跨平台计算机视觉基础库，提供图像处理、几何变换、特征提取、视频分析与深度学习推理等大量工程级算子和统一接口。',
    problem: '`borderInterpolate()` 通过 while 循环逐次把越界坐标折回图像范围。对 `INT_MIN` 取负会发生有符号整数溢出；对 `INT_MAX` 且边长为 2 的输入，则需要约十亿次折返。一个合法边界查询因此既可能触发未定义行为，也可能把常数时间像素访问拖成超长循环。',
    reasoning: '`BORDER_REFLECT` 与 `BORDER_REFLECT_101` 都是固定周期的离散映射，不需要模拟每次撞边。只要先在 64 位整数域中计算坐标相对周期的位置，再按两种模式各自的端点重复规则折回，就能覆盖完整 `int` 输入域并保持普通坐标的既有结果。',
    solution: '删除逐次反射循环，使用 `int64` 周期模运算一次得到规范位置，并显式处理负余数、长度为 1 以及两种 reflect 周期差异；回归将新旧映射在 20,010 组普通组合上逐项对照，再覆盖 `INT_MIN`、`INT_MAX` 与极小/极大边长。',
    impact: '反射插值在完整 32 位坐标范围内不再溢出，也不会因坐标距离增长而增加循环次数，最坏复杂度从 O(N) 降为 O(1)；普通输入与历史映射保持一致，极端边界同时经过 AddressSanitizer 和 UndefinedBehaviorSanitizer 验证。',
    highlight: 'O(N) → O(1)',
    takeaway: '极端反射坐标从十亿次循环降为常数时间',
    visualization: 'reflection',
  },
  {
    slug: 'deepspeed', name: 'DeepSpeed', logo: 'https://github.com/deepspeedai.png?size=128', accent: '#2859a8', role: 'CONTRIBUTOR', href: 'https://github.com/deepspeedai/DeepSpeed', prHref: 'https://github.com/deepspeedai/DeepSpeed/pull/8274',
    function: '面向大模型训练与推理的分布式深度学习优化系统，通过 ZeRO、并行训练、通信优化与内存管理降低超大模型的训练成本，并提升多 GPU / 多节点执行效率。',
    problem: 'ZenFlow 配置曾接受 `topk_ratio=0/1` 以及非正数 `update_interval`，训练初始化后可能分别触发梯度归一化除零和非法调度；即使比例合法，ZeRO-1/2 的小分区也可能因整数截断选择 0 列，进一步让 `torch.topk(k=0)` 与缓冲区尺寸失去有效语义。',
    reasoning: '自动更新路径同时除以 `topk_ratio` 与 `1-topk_ratio`，显式更新路径执行 `micro_step // update_interval`，因此两组除数都必须在配置边界被约束。对小比例选择，还必须以分区为单位统一计算选择数，并让索引缓冲区、梯度缓冲区和实际选择逻辑复用同一公式。',
    solution: '将比例约束为严格的 `(0,1)`，要求数值更新间隔至少为 1；新增共享的分区选择计数逻辑：空分区保持 0，非空分区使用 `max(1, int(columns × ratio))`，并同步应用到两条选择路径及对应缓冲区分配。',
    impact: '非法配置现在会在训练启动前直接失败，不再把除零和非法调度延迟到训练中；`topk_ratio=0.01` 与 50 列参数等小比例场景在 ZeRO-1/2 中仍保持非空选择，索引、梯度缓冲区与实际分区选择严格对齐。',
    highlight: 'VALIDATE → SELECT → ALLOCATE',
    takeaway: '训练前拦截非法配置，小比例分区也不再空选',
    release: {
      label: 'v0.19.6',
      title: 'PR #8274 已随 DeepSpeed v0.19.6 正式发布',
      href: 'https://github.com/deepspeedai/DeepSpeed/releases/tag/v0.19.6',
      credit: 'v0.19.6 Release Notes 直接列出 ZenFlow 比例与更新间隔边界修复，并在 New Contributors 中记录 @tandede 的首次贡献。',
      steps: ['ZenFlow 配置边界修复', 'Release Notes 收录 PR #8274', 'New Contributors 官方署名'],
    },
    visualization: 'zenflow',
  },
  {
    slug: 'openai-agents-sdk', name: 'OpenAI Agents SDK', logo: '/logos/openai.png', accent: '#111827', role: 'CONTRIBUTOR', href: 'https://github.com/openai/openai-agents-python', prHref: 'https://github.com/openai/openai-agents-python/pull/4512',
    function: '面向生产级 Agent 应用的轻量编排框架，统一 Agent、Tool、Handoff、Guardrail、Tracing 与 MCP 接入，支持构建可观测的多 Agent 工作流。',
    problem: '可视化扩展直接用 Agent、Tool、MCP Server 与 Handoff 的显示名生成 Graphviz node ID。不同实体一旦同名，就会被 DOT 合并为同一节点，真实连接退化成伪自环；同名 Agent 还可能被 `visited` 提前判定为已遍历，导致后续分支和节点完全消失。',
    reasoning: '显示名称只负责可读性，不能同时承担实体身份。一次渲染中的节点注册、递归遍历和边生成必须共享按对象区分的稳定 ID；同时还要兼容调用方传入的 visited 名称、虚拟 start 节点以及 DOT 转义后才发生的 CR/LF 名称碰撞。',
    solution: '新增每次渲染独立的实体身份注册表，以对象身份分配 node ID、保留原名称作为 label，并让直接 Handoff 与动态 `handoff()` 目标走同一遍历链；只在发生冲突或命中保留虚拟名时生成确定性后缀，避免改变无冲突图的既有 DOT 输出。',
    impact: '不同类型或不同实例即使同名也会保留为独立节点，边不再折叠成自环，所有可达 Agent 都能被完整遍历；转义碰撞、虚拟节点冲突和外部 visited 状态均有回归覆盖，19 项可视化测试锁定新的身份模型。',
    highlight: 'IDENTITY ≠ LABEL',
    takeaway: '实体身份与显示名称分离，工作流图不再错连',
    visualization: 'identity',
  },
  {
    slug: 'peft', name: 'PEFT', logo: '/logos/huggingface.png', accent: '#d69300', role: 'CONTRIBUTOR', href: 'https://github.com/huggingface/peft', prHref: 'https://github.com/huggingface/peft/pull/3559',
    function: 'Hugging Face 的参数高效微调框架，通过 LoRA、IA³、AdaLoRA 等方法只训练少量参数，降低 Transformer 与 Diffusion 模型适配成本。',
    problem: '`PeftModel.add_adapter()` 与 `PeftMixedModel.add_adapter()` 接受已经存在的 `adapter_name` 时，会先覆盖配置并再次向模型注入 Adapter 层。原有训练权重可能被重新初始化；如果后续注入失败，回滚逻辑甚至可能删除原来的配置，使一次非法调用留下部分修改状态。',
    reasoning: '这不是普通的重名提示，而是模型状态的原子性边界：公开 API 已约定名称唯一，冲突必须在任何配置写入、模块注入或权重初始化之前失败。与此同时，Prompt Learning 初始化与 `load_adapter` 的正常路径仍需经过同一入口，不能被新校验误伤。',
    solution: '在两个 `add_adapter` 入口最前方检查名称是否已注册，冲突立即抛出明确的 `ValueError`；Prompt Learning 初始化改为空注册表后再通过统一入口添加首个 Adapter，`load_adapter` 则保持仅在名称不存在时调用该路径。回归同时比对异常前后的配置与全部权重。',
    impact: '重复名称从静默覆盖变为修改前失败，已有 Adapter 的配置、结构和训练权重在异常路径中保持逐项不变；Prompt Learning、Mixed Model 与正常加载行为继续可用。相关定向与扩展测试共覆盖 1,400 余个用例，模型状态不再出现半提交。',
    highlight: 'FAIL BEFORE MUTATE',
    takeaway: '在修改模型之前拒绝重复 Adapter',
    visualization: 'adapter',
  },
  {
    slug: 'ultralytics-yolo', name: 'Ultralytics YOLO', logo: '/logos/ultralytics.png', accent: '#052251', role: 'CONTRIBUTOR', href: 'https://github.com/ultralytics/ultralytics', prHref: 'https://github.com/ultralytics/ultralytics/pull/25855',
    function: '覆盖目标检测、实例分割、图像分类、姿态估计与多目标跟踪的视觉平台，提供从数据训练到部署推理的一体化 Python 与 CLI 工作流。',
    problem: '数据集预先执行非等比例 resize，再由 `LetterBox(scale_fill=True)` 拉伸输入时，垂直与水平缩放率并不相同；旧 `ratio_pad` 却只保留前置 resize，`scale_boxes()` / `scale_coords()` 又统一除以第一个 gain，导致框、关键点和分割坐标恢复后发生轴向拉伸，并可能被错误裁到图像边界。',
    reasoning: '坐标逆变换必须严格逆序复原完整预处理链。前置 resize 的 `(gain_h, gain_w)` 要与 LetterBox 自身的双轴 ratio 分别相乘，padding 再按对应轴扣除；只有在等比例路径中两个 gain 才可以退化成同一个标量，不能把这个特例当作通用假设。',
    solution: '保存 `ratio_pad` 时组合两阶段的高度与宽度增益，并让 `scale_boxes` 与 `scale_coords` 分别使用 `gain_h`、`gain_w` 恢复 y/x 坐标；保留从图像形状自动推导的等比例行为，同时加入 stretched LetterBox 的端到端回归，对照原图上的框与坐标。',
    impact: '非方形输入和 `scale_fill=True` 场景中的检测框、关键点与分割坐标重新准确映射到原图，不再出现单轴漂移或边界误裁；默认等比例流程保持原有输出。完整 Python 测试 134 项通过，并覆盖双轴恢复与默认 ratio-pad 两条路径。',
    highlight: 'SCALE X ≠ SCALE Y',
    takeaway: '分别还原 x / y 轴，让预测结果准确回到原图',
    release: {
      label: 'v8.4.126',
      title: 'PR #25855 已随 Ultralytics v8.4.126 正式发布',
      href: 'https://github.com/ultralytics/ultralytics/releases/tag/v8.4.126',
      credit: 'v8.4.126 是合并后的首个正式版本，版本标签完整包含非等比例 ratio-pad 坐标恢复修复；该项未被单独写入版本摘要，因此这里只陈述可由标签提交关系验证的收录事实。',
      steps: ['双轴 ratio-pad 恢复', 'v8.4.126 标签包含合并提交', '正式版本已发布'],
    },
    visualization: 'axis',
  },
  {
    slug: 'timm', name: 'timm', logo: '/logos/huggingface.png', accent: '#d69300', role: 'CONTRIBUTOR', href: 'https://github.com/huggingface/pytorch-image-models', prHref: 'https://github.com/huggingface/pytorch-image-models/pull/2739',
    function: '大规模 PyTorch 图像模型库，汇集分类与视觉骨干网络、预训练权重、数据增强和训练工具，是视觉模型研究与复现的重要基础设施。',
    problem: '`rand_bbox_minmax()` 把 `img_h - cut_h` 与 `img_w - cut_w` 直接传给上界排除的 `numpy.random.randint`。因此裁剪框永远不能从最下方或最右方的最后一个合法坐标开始；框越接近整图，这两个被遗漏位置占全部候选的比例越高，长期训练会形成稳定的空间采样偏差。',
    reasoning: '合法起点是闭区间 `[0, image_size - cut_size]`，而 `randint` 接收的是半开区间。修复只应补回最后一个端点，不能改变框尺寸、批量采样形状或 CutMix 的 lambda 校正；验证还要覆盖 scalar 与 batched 两种边界框生成路径。',
    solution: '将高度与宽度采样上界各增加 1，使最终合法起点进入随机区间；新增固定随机种子的标量/批量回归，直接断言右侧与底部端点可达，并对四个合法位置执行 200,000 次采样，检查每个起点的频率近似均匀。',
    impact: 'CutMix minmax 现在覆盖完整的空间起点集合，右边界与下边界不再系统性欠采样，同时保持裁剪尺寸和 lambda 语义不变；大样本验证中四个位置的最大频率偏差仅 0.162 个百分点，相关 470 项测试通过。',
    highlight: 'FULL BOUNDARY COVERAGE',
    takeaway: '补回 CutMix 从未采到的右侧与底部边界',
    release: {
      label: 'v1.0.29',
      title: 'PR #2739 已随 timm v1.0.29 正式发布',
      href: 'https://github.com/huggingface/pytorch-image-models/releases/tag/v1.0.29',
      credit: 'v1.0.29 Release Notes 直接列出 CutMix minmax 边界采样修复，并在 New Contributors 中记录 @tandede 的首次贡献。',
      steps: ['CutMix 完整边界采样', 'Release Notes 收录 PR #2739', 'New Contributors 官方署名'],
    },
    visualization: 'boundary',
  },
  {
    slug: 'supervision', name: 'Supervision', logo: '/logos/supervision.png', accent: '#6f3ea3', role: 'CONTRIBUTOR', href: 'https://github.com/roboflow/supervision', prHref: 'https://github.com/roboflow/supervision/pull/2491',
    function: '面向计算机视觉工程的通用工具库，覆盖检测结果表示、几何计算、标注渲染、视频跟踪与数据集处理，连接模型输出与业务分析。',
    problem: '`sv.get_polygon_center()` 直接沿用输入数组的数据类型计算鞋带公式。大整数顶点会在 `int32` 乘法阶段先溢出；即使转成浮点，所有坐标都带有很大的绝对偏移时，两个接近的大面积矩相减仍会发生灾难性消减，使质心偏离多边形甚至落到完全错误的位置。',
    reasoning: '质心对整体平移保持等价，因此没有必要用远离原点的大数完成面积积分。先把计算域提升到 `float64` 解决整数乘积范围，再选取首个顶点作为局部原点缩小中间量，才能同时处理溢出与数值条件，而不是只修复其中一种症状。',
    solution: '将所有数值 ndarray 坐标统一转换为 `float64`，减去首顶点后在局部坐标中计算有向面积和质心，最后把原点加回全局结果；同步放宽公开类型标注，并加入 `int32` 乘法溢出、万亿级坐标偏移和零面积多边形回归。',
    impact: '大图像、地理坐标和远离原点的多边形现在都能稳定计算质心；平移前后的几何结果保持等价，int32 溢出与大数消减不再把质心推离真实位置。普通小坐标输入继续得到与原实现一致的结果。',
    highlight: 'LOCAL ORIGIN + FLOAT64',
    takeaway: '局部坐标加 float64，稳定计算大坐标质心',
    release: {
      label: 'v0.30.1',
      title: 'PR #2491 已随 Supervision v0.30.1 正式发布',
      href: 'https://github.com/roboflow/supervision/releases/tag/0.30.1',
      credit: '这项多边形质心数值稳定性修复已经进入用户可安装的正式版本，并由项目方在版本说明中单独列出；Zhewen Tan（@tandede）同时出现在该版本的 Contributors 名单中。',
      steps: ['数值精度与稳定性修复', 'Release Notes 收录 PR #2491', 'Contributors 官方署名'],
    },
    visualization: 'coordinate',
  },
  {
    slug: 'funasr', name: 'FunASR', logo: '/logos/funasr.png', accent: '#5368d9', role: 'CONTRIBUTOR', href: 'https://github.com/modelscope/FunASR', prHref: 'https://github.com/modelscope/FunASR/pull/3516',
    function: '面向语音识别研究与部署的完整工具箱，支持模型训练、离线与流式推理、语音端点检测、标点恢复以及说话人日志等能力。',
    problem: '`ClusterBackend` 在设置 `preset_spk_num` 后仍把所有规模的说话人嵌入送进谱聚类。长录音超过 2,048 个片段时，这条路径会构造 O(N²) 的稠密 affinity / Laplacian 矩阵并执行 O(N³) 特征分解；10,639 个片段即使已知只有两位说话人，也会失去原有的大规模保护。',
    reasoning: '样本规模决定谱方法是否可承受，说话人数是否已知决定是否还需要从谱结构估计簇数。已知 K 的大输入可以直接优化固定簇目标；但为了维持余弦相似度语义，K-means 前需要先对嵌入做 L2 归一化，并固定初始化确保多次运行可复现。',
    solution: '保留 2,048 以下的谱聚类和未知 K 大输入的 UMAP/HDBSCAN，仅为“大输入 + 已知 K”新增分支：先 L2 归一化说话人向量，再以请求的簇数运行确定性 K-means；回归同时锁定阈值处分发和实际聚类结果。',
    impact: '10,639×192 的合成说话人嵌入在 CPU 上约 0.098 秒完成，返回恰好两个簇并达到 100% 分离纯度，不再分配稠密相似矩阵；小样本和自动估计说话人数的原有算法保持不变，长音频获得有界内存路径。',
    highlight: 'NO DENSE N² MATRIX',
    takeaway: '已知 K 时绕开 O(N²) 稠密相似矩阵',
    release: {
      label: 'v1.4.5',
      title: 'PR #3516 已随 FunASR v1.4.5 正式发布',
      href: 'https://github.com/modelscope/FunASR/releases/tag/v1.4.5',
      credit: 'v1.4.5 是合并后的首个正式版本，版本标签完整包含长音频已知说话人数的聚类分流修复；版本摘要没有单独列出该 PR，因此不额外声称 Release Notes 署名。',
      steps: ['长音频聚类分流修复', 'v1.4.5 标签包含合并提交', '正式版本已发布'],
    },
    visualization: 'routing',
  },
  {
    slug: 'burn', name: 'Burn', logo: '/logos/burn.png', accent: '#b44313', role: 'CONTRIBUTOR', href: 'https://github.com/tracel-ai/burn', prHref: 'https://github.com/tracel-ai/burn/pull/5394',
    function: '以 Rust 构建的跨平台深度学习框架，兼顾训练、推理、自动微分和多后端部署，强调类型安全、性能以及从桌面到嵌入式设备的可移植性。',
    problem: 'Burn Flex 的 depthwise 与 small-channel 卷积快速路径会跳过 padding 区域，而通用 im2col 路径会把这些位置显式物化为 0。有限权重下两者等价，但 IEEE 754 规定 `0 × Inf` 与 `0 × NaN` 结果为 NaN；仅改变通道数就可能让同一卷积的边界输出在有限值、Inf 与 NaN 之间变化。',
    reasoning: '不能简单让所有 padded 卷积回退到通用实现，否则罕见异常值会拖慢全部正常模型。真正需要修正的仅是“非有限权重参与了被省略的零 padding 项”的输出位置；无 padding、全有限权重以及其他通道都应继续复用现有向量化累加。',
    solution: '在进入带 padding 的快速路径时只扫描一次权重是否含非有限值，并精确标记哪些输出位置省略了对应的零乘项；保留原有向量化计算，再仅对受影响位置恢复 NaN 语义。回归覆盖 small-channel、generic、depthwise 三条分发及跨通道隔离。',
    impact: '快速路径与通用 im2col 路径现在对 Inf / NaN 产生一致的 IEEE 754 结果，非有限权重不会污染无关通道；有限权重仍走原有热路径，无 padding 时连额外扫描也不会发生。Burn Flex 相关 741 项测试及 19 项后端卷积测试通过。',
    highlight: 'IEEE 754 + FAST PATH',
    takeaway: '保留卷积快速路径，同时恢复 IEEE 754 语义',
    release: {
      label: 'v0.22.0-pre.3',
      title: 'PR #5394 已进入 Burn v0.22.0-pre.3 预发布版',
      href: 'https://github.com/tracel-ai/burn/releases/tag/v0.22.0-pre.3',
      credit: 'Burn 的官方预发布说明直接列出“preserve non-finite padding semantics in conv”并署名 @tandede。该版本仍是 pre-release，因此不将其表述为稳定版本。',
      steps: ['卷积非有限 padding 语义修复', '预发布说明收录 PR #5394', '官方署名 @tandede'],
      linkLabel: '查看预发布版本',
    },
    visualization: 'numeric',
  },
  {
    slug: 'nltk', name: 'NLTK', logo: 'https://github.com/nltk.png?size=128', accent: '#154f7d', role: 'CONTRIBUTOR', href: 'https://github.com/nltk/nltk', prHref: 'https://github.com/nltk/nltk/pull/3773',
    function: '经典自然语言处理工具库，覆盖分词、词性标注、句法与语义分析、语料库接口和教学资源，为 NLP 研究、原型验证与课程实践提供稳定基础设施。',
    problem: 'chat80.Concept 的 altLabels、closures 与 extension 使用可变默认参数，多个默认构造实例会静默共享同一组容器；修改一个概念，后续概念的状态也会被污染。',
    reasoning: '根因不是 chat80 数据内容，而是 Python 默认参数只在函数定义时创建一次。三个容器跨实例复用，因此对象表面独立，底层状态实际相连；显式传入的容器则应继续保留调用者语义。',
    solution: '将三个可变默认值替换为 None 哨兵，仅在调用者未提供容器时为当前实例创建新的 list 与 set，同时保留显式传入容器，并加入双实例状态隔离回归用例。',
    impact: 'Concept 实例恢复真正的状态隔离：修改一个对象的标签、闭包或扩展集合，不再改变随后创建的对象；显式传入的容器仍按调用者意图保留引用。回归同时覆盖三个默认容器与双实例交叉修改。',
    highlight: 'INSTANCE STATE ISOLATED',
    takeaway: '按实例创建默认容器，消除跨对象状态泄漏',
    visualization: 'shared-state',
  },
  {
    slug: 'apache-tvm', name: 'Apache TVM', logo: 'https://github.com/apache.png?size=128', accent: '#d1492e', role: 'CONTRIBUTOR', href: 'https://github.com/apache/tvm', prHref: 'https://github.com/apache/tvm/pull/20161',
    function: '面向深度学习模型的开源编译器栈，将来自 ONNX、PyTorch 等框架的计算图导入统一中间表示，并针对不同硬件完成图优化、算子生成与高性能部署。',
    problem: 'Relax ONNX 导入器没有正确区分 Reshape 的零值语义：默认模式下 `[0, 3]` 未先复制输入维度便进入 NumPy 常量折叠；`allowzero=1` 时又会触发 Relax 自身的零复制规则，无法保留字面零维。',
    reasoning: 'ONNX 的 `0` 同时受 `allowzero` 控制，而 `-1` 仍负责维度推断。特殊处理不能覆盖所有 `allowzero=1` 情况，否则没有字面零的 `[-1, 2]` 也会绕过正常推断并在运行期失败。',
    solution: '默认模式先把目标形状中的 `0` 规范化为对应输入维度再做常量折叠；仅当 `allowzero=1` 且目标形状确实含有字面零时构造 ShapeExpr，其余情况继续使用正常 Reshape 路径保留 `-1` 推断。',
    impact: '同时覆盖默认零复制、真实零维输出与动态 `-1` 推断三条路径，使 ONNX 模型语义能够忠实落到 Relax；没有字面零的形状继续走正常推断路径，避免特殊分支扩大后造成新的运行期失败。',
    highlight: '0 COPY · 0 LITERAL · −1 INFER',
    takeaway: '同时保留零复制、字面零与 −1 推断语义',
    visualization: 'reshape-semantics',
  },
  {
    slug: 'torchvision', name: 'Torchvision', logo: 'https://github.com/pytorch.png?size=128', accent: '#ee4c2c', role: 'CONTRIBUTOR', href: 'https://github.com/pytorch/vision', prHref: 'https://github.com/pytorch/vision/pull/9615',
    function: 'PyTorch 官方计算机视觉库，提供主流视觉数据集、预训练模型、图像与视频变换以及高性能算子，是视觉训练和推理工作流中的核心基础设施。',
    problem: '`transforms.v2.JPEG` 支持形如 `[..., C, H, W]` 的任意前导批次维度，但内核使用 `view()` 展平批次轴；一旦输入由 transpose 等操作产生非连续布局，合法 Tensor 会在进入 JPEG 编码前直接报错。',
    reasoning: 'Tensor 的逻辑形状与底层内存是否连续是两个维度。这里需要的是保持逻辑元素顺序的展平，而不是强制要求调用方先复制；`reshape()` 在布局兼容时仍返回视图，仅在必要时才物化连续副本，正好覆盖这条语义边界。',
    solution: '将 JPEG v2 内核的前导维展平从 `view()` 改为 `reshape()`，编码完成后继续恢复原始形状；同时用转置批次轴构造真实的非连续输入，并与其 contiguous 等价输入对照，锁定多前导维场景。',
    impact: '非连续批次 Tensor 现在可以直接进入 JPEG 变换，无需用户手动调用 `.contiguous()`；原有连续输入仍沿零额外复制路径执行，接口承诺与 PyTorch 的 Tensor 布局语义重新一致。',
    highlight: 'LOGICAL SHAPE ≠ MEMORY LAYOUT',
    takeaway: '非连续批次无需手动 contiguous 也能编码 JPEG',
    visualization: 'tensor-layout',
  },
  {
    slug: 'lerobot', name: 'LeRobot', logo: 'https://github.com/huggingface.png?size=128', accent: '#d69300', role: 'CONTRIBUTOR', href: 'https://github.com/huggingface/lerobot', prHref: 'https://github.com/huggingface/lerobot/pull/4488',
    function: 'Hugging Face 面向真实机器人学习的开源平台，覆盖数据采集与可视化、机器人数据集、模仿学习策略、预训练模型和硬件接入，让端到端机器人学习更易复现与部署。',
    problem: '`aggregate_datasets` 接收一一对应的 `repo_ids` 与 `roots`，旧实现却使用非严格 `zip`；当根目录数量更少时，尾部源数据集会被静默截断，聚合任务可能在数据缺失的情况下继续完成。',
    reasoning: '两个列表共同描述同一组数据源，长度相等是公开 API 的前置不变量。依赖普通 `zip` 不仅掩盖非法输入，还会在已经读取部分数据后才暴露无关错误，因此必须在任何元信息加载前验证这条边界。',
    solution: '在聚合入口显式校验 `roots` 与 `repo_ids` 数量完全一致，不匹配时立即抛出清晰的 `ValueError`；校验通过后再使用 strict pairing，使后续实现也无法重新引入静默截断。',
    impact: '无效聚合请求在触碰数据集前就会失败，避免机器人训练数据悄然缺失、来源数量与产物不一致；合法调用保持原有行为，数据聚合链路获得可验证的完整性保证。',
    highlight: 'SILENT DROP → FAIL FAST',
    takeaway: '聚合前校验并行输入，阻止数据集被静默截断',
    visualization: 'parallel-inputs',
  },
];
